// Batch import data - paste this in browser console
const townsList = [
"Vilobí d'Onyar","Aiguafreda","Aiguaviva","Albinyana","Alforja","Altafulla","Amer","Anglès","Arbúcies","Arenys de Mar","Esparreguera","Igualada","Olot","Olèrdola","Balenya","Banyeres del Penedès","Banyoles","Begues","Bellver de Cerdanya","Berga","Bescanó","Bigues i Riells","Blanes","Breda","Cabrera d'Anoia","Cadaqués","Calella","Calldetenes","Callus","Camarles","Cambrils","Campelles","Campllong","Camprodon","Camós","Canet d'Adri","Canovelles","Canyelles","Capellades","Cardedeu","Cardona","Castell-Platja D'Aro","Castellar del Vallés","Castellbisbal","Castellcir","Castellgali","Castellnou de Bages","Castelloli","Castellvell del Camp","Castellvi de la Marca","Castelló D'Empuries","Centelles","Cervera","Collsuspina","Corbera de Llobregat","Cornella de Llobregat","Creixell","Cunit","Canoves","El Bruc","Montmany- Figaro","Flaçà","Folgueroles","Fornells de la Selva","Fortià","Girona","Gualba","Jorba","L'Ampolla","Escala, L'","L'Esquirol","La Bisbal d'Empordà","La Garriga","La Granada","La Pera","La Pobla de Claramunt","La Riba","Les Cabanyes","Les Masies de Roda","Planes d'Hostoles","Linyola","Lleida","Llinars del Valles","Lliça D'Amunt","Maià de Montcal","Malgrat de Mar","Manlleu","Manresa","Martorell","Martorelles","Masquefa","Massanes","Matadepera","Mataro","Maçanet de la Selva","Molins de Rei","Molló","Mont-ras","Mont-roig del Camp","Montblanc","Montesquiu","Montgat","Montmelo","Navarcles","Navata","Palafolls","Palafrugell","Palamós","Palau-Solità i Plegamans","Pallejà","Palol de Revardit","Pals","Parets del Vallès","Piera","Pineda de Mar","Prats de Lluçanès","Ribes de Freser","Riells I Viabrea","Riudarenes","Roda de Berà","Sallent","Sant Andreu de la Barca","Sant Aniol de Finestres","San Celoni","Sant Cugat del Vallès","Sant Cugat Sesgarrigues","Sant Feliu de Codines","Sant Feliu de Guixols","Sant Feliu de Pallerols","Sant Fruitos de Bages","Sant Gregori","Sant Hilari Sacalm","Sant Jaume dels Domenys","Sant Joan de Vilatorrada","Sant Julià de Vilatorta","Sant Llorenç d'Hortons","Sant Llorenç de la Muga","Sant Martí de Centelles","Sant Martí de Llèmena","Sant Martí de Tous","Sant Pau de Segúries","Sant Pere de Ribes","Sant Pere de Vilamajor","Sant Pol de Mar","Sant Quinti de Mediona","Sant Quirze de Besora","Sant Quirze del Vallès","Sant Vicenç de Torello","Santa Coloma de Farnérs","Santa Cristina D'Aro","Santa Eugènia de Berga","Santa Eulalia de Ronçana","Santa Margarida de Montbuí","Santa María d'Oló","Santa Maria de Besora","Santa Maria de Palautordera","Santa Oliva","Santa Pau","Santa Perpetua de Mogoda","Santa Susanna","Sarrià de Dalt","Saus Camallera I Llampaies","Sentmenat","Sils","Sitges","Siurana","Solsona","Subirats","Susqueda","Súria","Taradell","Tarragona","Teià","Tordera","Torredembarra","Torrelavit","Torrelles de Llobregat","Torrent","Torroella de Montgri","Tossa de Mar","Vall-llobrega","Vallbona D'Anoia","Vallgorguina","Vallirana","Vallromanes","Valls","Vandellòs i l'Hospitalet de L'Infant","Vidreres","Vidrà","Vilablareix","Viladrau","Vilalba Sasserra","Vilallonga de Ter","Vilanova del Camí","Vilanova del Vallès","Vilaverd","El Far d'Empordà","Juncosa de Montmell","El Morell","El Palau d'Anglesola","El Papiol","El Pla del Penedès","El Vendrell","Els Pallaresos","El Pla de Santa Maria","La Cellera de Ter","El Pont de Vilomara I Rocafort","Sant Julià del Llor i Bonmatí","Sant Salvador de Guardiola"
];

async function batchAddTowns() {
    console.log(`📋 Starting batch import of ${townsList.length} towns...`);
    let addedCount = 0, skippedCount = 0;
    
    for (const town of townsList) {
        const existing = clients.find(c => c.name.toLowerCase() === town.toLowerCase());
        if (existing) { skippedCount++; continue; }
        
        try {
            // Use allorigins CORS proxy
            const proxyUrl = `https://api.allorigins.win/raw?url=${encodeURIComponent('https://nominatim.openstreetmap.org/search?q=' + encodeURIComponent(town) + ', Spain&format=json&limit=1')}`;
            const response = await fetch(proxyUrl);
            const data = await response.json();
            
            if (data.length > 0) {
                const result = data[0];
                const townName = town.split(',')[0].trim().toLowerCase();
                let detectedComarca = townToComarca[townName] || 'cat';
                
                const client = {
                    id: Date.now() + Math.random(),
                    name: result.display_name,
                    lat: parseFloat(result.lat),
                    lng: parseFloat(result.lon),
                    projects: [],
                    groupId: detectedComarca,
                    services: { mantenimiento: { active: false, expiryDate: null }, adm: { active: false, expiryDate: null } }
                };
                clients.push(client);
                addedCount++;
                console.log(`✅ Added: ${town}`);
            } else {
                skippedCount++;
                console.log(`⚠️ Not found: ${town}`);
            }
        } catch (error) {
            skippedCount++;
            console.log(`❌ Error: ${town}`);
        }
        // Longer delay to avoid rate limiting
        await new Promise(resolve => setTimeout(resolve, 300));
    }
    
    console.log(`\n✅ Done! Added: ${addedCount}, Skipped: ${skippedCount}`);
    autoSaveToFirebase();
    updateDisplay();
}

batchAddTowns();
"Aiguafreda",
"Aiguaviva",
"Albinyana",
"Alforja",
"Altafulla",
"Amer",
"Anglès",
"Arbúcies",
"Arenys de Mar",
"Esparreguera",
"Igualada",
"Olot",
"Olèrdola",
"Balenya",
"Banyeres del Penedès",
"Banyoles",
"Begues",
"Bellver de Cerdanya",
"Berga",
"Bescanó",
"Bigues i Riells",
"Blanes",
"Breda",
"Cabrera d'Anoia",
"Cadaqués",
"Calella",
"Calldetenes",
"Callus",
"Camarles",
"Cambrils",
"Campelles",
"Campllong",
"Camprodon",
"Camós",
"Canet d'Adri",
"Canovelles",
"Canyelles",
"Capellades",
"Cardedeu",
"Cardona",
"Castell-Platja D'Aro",
"Castellar del Vallés",
"Castellbisbal",
"Castellcir",
"Castellgali",
"Castellnou de Bages",
"Castelloli",
"Castellvell del Camp",
"Castellvi de la Marca",
"Castelló D'Empuries",
"Centelles",
"Cervera",
"Collsuspina",
"Corbera de Llobregat",
"Cornella de Llobregat",
"Creixell",
"Cunit",
"Canoves",
"El Bruc",
"Montmany- Figaro",
"Flaçà",
"Folgueroles",
"Fornells de la Selva",
"Fortià",
"Girona",
"Gualba",
"Jorba",
"L'Ampolla",
"Escala, L'",
"L'Esquirol",
"La Bisbal d'Empordà",
"La Garriga",
"La Granada",
"La Pera",
"La Pobla de Claramunt",
"La Riba",
"Les Cabanyes",
"Les Masies de Roda",
"Planes d'Hostoles",
"Linyola",
"Lleida",
"Llinars del Valles",
"Lliça D'Amunt",
"Maià de Montcal",
"Malgrat de Mar",
"Manlleu",
"Manresa",
"Martorell",
"Martorelles",
"Masquefa",
"Massanes",
"Matadepera",
"Mataro",
"Maçanet de la Selva",
"Molins de Rei",
"Molló",
"Mont-ras",
"Mont-roig del Camp",
"Montblanc",
"Montesquiu",
"Montgat",
"Montmelo",
"Navarcles",
"Navata",
"Palafolls",
"Palafrugell",
"Palamós",
"Palau-Solità i Plegamans",
"Pallejà",
"Palol de Revardit",
"Pals",
"Parets del Vallès",
"Piera",
"Pineda de Mar",
"Prats de Lluçanès",
"Ribes de Freser",
"Riells I Viabrea",
"Riudarenes",
"Roda de Berà",
"Sallent",
"Sant Andreu de la Barca",
"Sant Aniol de Finestres",
"San Celoni",
"Sant Cugat del Vallès",
"Sant Cugat Sesgarrigues",
"Sant Feliu de Codines",
"Sant Feliu de Guixols",
"Sant Feliu de Pallerols",
"Sant Fruitos de Bages",
"Sant Gregori",
"Sant Hilari Sacalm",
"Sant Jaume dels Domenys",
"Sant Joan de Vilatorrada",
"Sant Julià de Vilatorta",
"Sant Llorenç d'Hortons",
"Sant Llorenç de la Muga",
"Sant Martí de Centelles",
"Sant Martí de Llèmena",
"Sant Martí de Tous",
"Sant Pau de Segúries",
"Sant Pere de Ribes",
"Sant Pere de Vilamajor",
"Sant Pol de Mar",
"Sant Quinti de Mediona",
"Sant Quirze de Besora",
"Sant Quirze del Vallès",
"Sant Vicenç de Torello",
"Santa Coloma de Farnérs",
"Santa Cristina D'Aro",
"Santa Eugènia de Berga",
"Santa Eulalia de Ronçana",
"Santa Margarida de Montbuí",
"Santa María d'Oló",
"Santa Maria de Besora",
"Santa Maria de Palautordera",
"Santa Oliva",
"Santa Pau",
"Santa Perpetua de Mogoda",
"Santa Susanna",
"Sarrià de Dalt",
"Saus Camallera I Llampaies",
"Sentmenat",
"Sils",
"Sitges",
"Siurana",
"Solsona",
"Subirats",
"Susqueda",
"Súria",
"Taradell",
"Tarragona",
"Teià",
"Tordera",
"Torredembarra",
"Torrelavit",
"Torrelles de Llobregat",
"Torrent",
"Torroella de Montgri",
"Tossa de Mar",
"Vall-llobrega",
"Vallbona D'Anoia",
"Vallgorguina",
"Vallirana",
"Vallromanes",
"Valls",
"Vandellòs i l'Hospitalet de L'Infant",
"Vidreres",
"Vidrà",
"Vilablareix",
"Viladrau",
"Vilalba Sasserra",
"Vilallonga de Ter",
"Vilanova del Camí",
"Vilanova del Vallès",
"Vilaverd",
"El Far d'Empordà",
"Juncosa de Montmell",
"El Morell",
"El Palau d'Anglesola",
"El Papiol",
"El Pla del Penedès",
"El Vendrell",
"Els Pallaresos",
"El Pla de Santa Maria",
"La Cellera de Ter",
"El Pont de Vilomara I Rocafort",
"Sant Julià del Llor i Bonmatí",
"Sant Salvador de Guardiola"
];
"Aiguamurcia",
"Aiguaviva",
"Aitona",
"Alcalà de Gurrea",
"Alcalà la Jovada",
"Alcalà la Vellea",
"Alcarr",
"Alcoletge",
"Aldover",
"Alegre de Dalt",
"Alfara de Carles",
"Alfara de Priorat",
"Algars",
"Algesiras",
"Algina",
"Alguaire",
"Alhama del Aragó",
"Aliança",
"Alivella",
"Allo",
"Almatret",
"Almudévar",
"Almunècar",
"Almussafes",
"Alonya",
"Alpens",
"Alpuente",
"Alsòndia",
"Altabriga",
"Altafulla",
"Altamira",
"Altamira de Linares",
"Altaona",
"Altava",
"Altaya",
"Altea",
"Alteró",
"Altet",
"Altimira",
"Altisiodor",
"Altissiodor",
"Altistac",
"Altobó",
"Altolaguirre",
"Altollano",
"Altolosa",
"Altomira",
"Altonaón",
"Altor de Bretones",
"Altorca",
"Altordo",
"Altoria",
"Altosa",
"Altosa de Cabrales",
"Altozano",
"Altreu",
"Altricia",
"Alturo",
"Altura",
"Alucebilla",
"Aludas",
"Alueche",
"Aluenda",
"Alugía",
"Alumbrada",
"Alumnadora",
"Alumine",
"Alumnilla del Arzobispo",
"Alumnisela",
"Alumnización",
"Alumnizo",
"Alumnonda",
"Alumnia",
"Alumnición",
"Alveara",
"Alveera",
"Alvega",
"Alveías",
"Alvelera",
"Alvena de Peralej",
"Alveñas",
"Alversón",
"Alvés",
"Alvesa",
"Alvesat",
"Alveta",
"Alvetana",
"Alveti",
"Alveto",
"Alvetosa",
"Alveya",
"Alveza",
"Alvezo",
"Alvi",
"Alvia",
"Alviar",
"Alviará",
"Alviaria",
"Alviario",
"Alvías",
"Alvica",
"Alvicea",
"Alvicena",
"Alvicia",
"Alvicies",
"Alvicocería",
"Alvicola",
"Alvidera",
"Alvideña",
"Alvidrera",
"Alvidrera de la Serna",
"Alvidrera de los Campos",
"Alvidrera Nueva",
"Alvidrera Vieja",
"Alvidrera y la Vega",
"Alvidrid",
"Alvidriera",
"Alvidro",
"Alvidros",
"Alviduela",
"Alviduelas",
"Alviduerna",
"Alvihuesa",
"Alvij",
"Alvija",
"Alvilejo",
"Alvilena",
"Alvileno",
"Alvileta",
"Alvilezno",
"Alvilez",
"Alvililla",
"Alvillar",
"Alvilleza",
"Alvillez",
"Alvillezno",
"Alvillezuela",
"Alvíllez",
"Alvillezuela",
"Alvillo",
"Alvillos",
"Alvillueca",
"Alvilluela",
"Alvimeda",
"Alvimira",
"Alvin",
"Alvina",
"Alvinales",
"Alvinales de Campos",
"Alvinales del Páramo",
"Alvinales Nuevos",
"Alvinales Viejos",
"Alvinancia",
"Alviñana",
"Alvinania",
"Alvinca",
"Alvinción",
"Alvinda",
"Alvinción de Campos",
"Alvinción de Tierra de Campos",
"Alvinda del Páramo",
"Alvinda Vega",
"Alvindale",
"Alvinela",
"Alvinera",
"Alvinería",
"Alvinés",
"Alvineta",
"Alvingano",
"Alvinganón",
"Alvini",
"Alviniana",
"Alvinianella",
"Alviniana Negra",
"Alviniania",
"Alvinicia",
"Alvinición",
"Alvinida",
"Alviniella",
"Alviniella",
"Alvinifera",
"Alvinilla",
"Alvinilla Nueva",
"Alvinilla Vieja",
"Alvinio",
"Alvinios",
"Alvinipeda",
"Alvinir",
"Alvinira",
"Alvinirán",
"Alvinisca",
"Alvinisquera",
"Alvinista",
"Alvinita",
"Alviña",
"Alvinada",
"Alvinadas",
"Alviñagual",
"Alviñal",
"Alviñalejo",
"Alviñalena",
"Alviñales",
"Alviñales de Campos",
"Alviñán",
"Alviñana",
"Alviñancia",
"Alviñanica",
"Alviñanicela",
"Alviñanico",
"Alviñancho",
"Alviñaní",
"Alviñanía",
"Alviñanilla",
"Alviñanino",
"Alviñanita",
"Alviñano",
"Alviñantela",
"Alviñanza",
"Alviñanzuela",
"Alviñardela",
"Alviñardilla",
"Alviñardón",
"Alviñarón",
"Alviñarraya",
"Alviñarrera",
"Alviñarrería",
"Alviñarril",
"Alviñarrilla",
"Alviñarrillo",
"Alviñarroba",
"Alviñarrola",
"Alviñarruela",
"Alviñarruelas",
"Alviñarruelo",
"Alviño",
"Alvinoche",
"Alvinochuela",
"Alvinojo",
"Alvinola",
"Alvinolada",
"Alvinolera",
"Alvinolilla",
"Alvinolina",
"Alvinolita",
"Alvinolonda",
"Alvinolosa",
"Alvinolota",
"Alvinoluela",
"Alvinoluela de la Orden",
"Alvinoluelas",
"Alvinoní",
"Alvinonia",
"Alvinóscula",
"Alvinos",
"Alvinota",
"Alvinota de Campos",
"Alvinota de la Order",
"Alvinota del Páramo",
"Alvinota de Moya",
"Alvinota de Orejana",
"Alvinota de Paredes",
"Alvinota de la Serena",
"Alvinota del Sorbe",
"Alvinota Vieja",
"Alvinotada",
"Alvinotadas",
"Alvinotadilla",
"Alvinotadillas",
"Alvinotadina",
"Alvinotadilla",
"Alvinotadilla Chiquita",
"Alvinotadilla Grandota",
"Alvinotadera",
"Alvinotadera de Campos",
"Alvinotaderilla",
"Alvinotaderilla de Campos",
"Alvinotaderilla del Páramo",
"Alvinotaderilla Nueva",
"Alvinotaderilla Vieja",
"Alvinotaderilla y Campo",
"Alvinotaderón",
"Alvinotaderuela",
"Alvinotadera Vega",
"Alvinotadezilla",
"Alvinotadezno",
"Alvinotadezuela",
"Alvinotadera",
"Alvinotadilla",
"Alvinotadilla Chica",
"Alvinotadilla Grana",
"Alvinotadilla Mayor",
"Alvinotadilla Menor",
"Alvinotadilla Pequeña",
"Alvinotadilla de Campos",
"Alvinotadilla de Fuente de Piedra",
"Alvinotadilla de Hueles",
"Alvinotadilla de la Laguna",
"Alvinotadilla de Páramo",
"Alvinotadilla de Pardomilla",
"Alvinotadilla de Peribáñez",
"Alvinotadilla de Salas",
"Alvinotadilla de Segovia",
"Alvinotadilla de Tordesillas",
"Alvinotadilla de Tordesillos",
"Alvinotadilla Desaparecida",
"Alvinotadilla del Páramo",
"Alvinotadilla Nueva",
"Alvinotadilla Vieja",
"Alvinotadilleja",
"Alvinotadilleja del Páramo",
"Alvinotadilleja Vieja",
"Alvinotadillela",
"Alvinotadillejana",
"Alvinotadillena",
"Alvinotadillena de Campos",
"Alvinotadillena de la Orden",
"Alvinotadillena de Páramo",
"Alvinotadillena Nueva",
"Alvinotadillena Vieja",
"Alvinotadillencia",
"Alvinotadillencia de Campos",
"Alvinotadillencia de la Orden",
"Alvinotadillencia de Páramo",
"Alvinotadillencia Nueva",
"Alvinotadillencia Vieja",
"Alvinotadillencia y Campo",
"Alvinotadillencia y Páramo",
"Alvinotadillengo",
"Alvinotadilleña",
"Alvinotadilleño",
"Alvinotadillez",
"Alvinotadillez de Campos",
"Alvinotadillez Nueva",
"Alvinotadillez Vieja",
"Alvinotadillez y Campos",
"Alvinotadillezna",
"Alvinotadillezno",
"Alvinotadillezuela",
"Alvinotadillezuelas",
"Alvinotadillibanda",
"Alvinotadillo",
"Alvinotadillos",
"Alvinotadillos de Campos",
"Alvinotadillos de Páramo",
"Alvinotadillos del Páramo",
"Alvinotadillos Nueva",
"Alvinotadillos Vieja",
"Alvinotadillosa",
"Alvinotadillosa de Campos",
"Alvinotadillosa de la Orden",
"Alvinotadillosa de Páramo",
"Alvinotadillosa Nueva",
"Alvinotadillosa Vieja",
"Alvinotadillósca",
"Alvinotadilloscano",
"Alvinotadilloscana",
"Alvinotadillosca",
"Alvinotadilloscas",
"Alvinotadilloscanía",
"Alvinotadilloscano",
"Alvinotadilloscanería",
"Alvinotadilloscanería de Campos",
"Alvinotadilloscanería Nueva",
"Alvinotadilloscanería Vieja",
"Alvinotadilloscanilla",
"Alvinotadilloscanilla de Campos",
"Alvinotadilloscanilla Nueva",
"Alvinotadilloscanilla Vieja",
"Alvinotadilloscanillazo",
"Alvinotadilloscanillazo de Campos",
"Alvinotadilloscanillazo Nueva",
"Alvinotadilloscanillazo Vieja",
"Alvinotadilloscanillejana",
"Alvinotadilloscanillejano",
"Alvinotadilloscanilleña",
"Alvinotadilloscanilleño",
"Alvinotadilloscanillez",
"Alvinotadilloscanillez de Campos",
"Alvinotadilloscanillez Nueva",
"Alvinotadilloscanillez Vieja",
"Alvinotadilloscanilla",
"Alvinotadilloscanillazo",
"Alvinotadilloscanilleja",
"Alvinotadilloscanillejo",
"Alvinotadilloscanillela",
"Alvinotadilloscanilla",
"Alvinotadilloscanilla de Campos",
"Alvinotadilloscanilla de Páramo",
"Alvinotadilloscanilla Nueva",
"Alvinotadilloscanilla Vieja",
"Alvinotadigada",
"Alvinota Grande",
"Alvinota Pequeña",
"Alvinotala",
"Alvinotalada",
"Alvinotaladera",
"Alvinotaladera de Campos",
"Alvinotaladera de Páramo",
"Alvinotaladera Nueva",
"Alvinotaladera Vieja",
"Alvinotaladerilla",
"Alvinotaladerilla de Campos",
"Alvinotaladerilla de Páramo",
"Alvinotaladerilla Nueva",
"Alvinotaladerilla Vieja",
"Alvinotaladerilla y Páramo",
"Alvinotaladerito",
"Alvinotaladerón",
"Alvinotaladeruelas",
"Alvinotaladera",
"Alvinotaladura",
"Alvinotalaguala",
"Alvinotalagualada",
"Alvinotalaguala de Campos",
"Alvinotalaguala Nueva",
"Alvinotalaguala Vieja",
"Alvinotalaguala y Campos",
"Alvinotálago",
"Alvinotalagrada",
"Alvinotalagrada Chica",
"Alvinotalagrada Grande",
"Alvinotalagrada Nueva",
"Alvinotalagrada Vieja",
"Alvinotalagrada y Campos",
"Alvinotalagradilla",
"Alvinotalagradilla de Campos",
"Alvinotalagradilla Nueva",
"Alvinotalagradilla Vieja",
"Alvinotalagradilla y Campos",
"Alvinotalagradillada",
"Alvinotalagradillado",
"Alvinotalagradilladora",
"Alvinotalagradilladora de Campos",
"Alvinotalagradilladora Nueva",
"Alvinotalagradilladora Vieja",
"Alvinotalagradilladora y Campos",
"Alvinotalagradillador",
"Alvinotalagradilladura",
"Alvinotalagradilladora",
"Alvinotalagradilladura",
"Alvinotalagradilladora",
"Alvinotalagradillado",
"Alvinotalagradeso",
"Alvinotalagradeza",
"Alvinotalagrado",
"Alvinotalagrado de Campos",
"Alvinotalagrado Nueva",
"Alvinotalagrado Vieja",
"Alvinotalagrador",
"Alvinotalagrado y Campos",
"Alvinotalagradorcilla",
"Alvinotalagradorcillo",
"Alvinotalagradorcillo de Campos",
"Alvinotalagradorcillo Nueva",
"Alvinotalagradorcillo Vieja",
"Alvinotalagradorcillo y Campos",
"Alvinotalagradorcina",
"Alvinotalagradorcina de Campos",
"Alvinotalagradorcina Nueva",
"Alvinotalagradorcina Vieja",
"Alvinotalagradorcina y Campos",
"Alvinotalagradorcino",
"Alvinotalagradorcina",
"Alvinotalagradorcina de Campos",
"Alvinotalagradorcina Nueva",
"Alvinotalagradorcina Vieja",
"Alvinotalagradorcina y Campos",
"Alvinotalagraduela",
"Alvinotalagrey",
"Alvinotalagría",
"Alvinotalagría de Campos",
"Alvinotalagría Nueva",
"Alvinotalagría Vieja",
"Alvinotalagría y Campos",
"Alvinotalagriada",
"Alvinotalagriador",
"Alvinotalagrie",
"Alvinotalagriela",
"Alvinotalagrieza",
"Alvinotalagriña",
"Alvinotalagriño",
"Alvinotalagriña",
"Alvinotalagriño",
"Alvinotalagría",
"Alvinotalaguela",
"Alvinotalaguela de Campos",
"Alvinotalaguela Nueva",
"Alvinotalaguela Vieja",
"Alvinotalaguelas",
"Alvinotalaguelas de Campos",
"Alvinotalaguelas Nueva",
"Alvinotalaguelas Vieja",
"Alvinotalaguería",
"Alvinotalagueruela",
"Alvinotalagueruela de Campos",
"Alvinotalagueruela Nueva"
];

async function batchAddTowns() {
    console.log(`📋 Starting batch import of ${townsList.length} towns...`);
    
    let addedCount = 0;
    let skippedCount = 0;
    
    for (const town of townsList) {
        // Check if town already exists
        const existing = clients.find(c => c.name.toLowerCase() === town.toLowerCase());
        if (existing) {
            skippedCount++;
            continue;
        }
        
        // Try to geocode the town
        try {
            const response = await fetch(`https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(town)}, Spain&format=json&limit=1`);
            const data = await response.json();
            
            if (data.length > 0) {
                const result = data[0];
                const townName = town.split(',')[0].trim().toLowerCase();
                let detectedComarca = townToComarca[townName];
                
                if (!detectedComarca) {
                    detectedComarca = 'cat'; // Default to Catalonia root
                }
                
                const client = {
                    id: Date.now() + Math.random(),
                    name: result.display_name,
                    lat: parseFloat(result.lat),
                    lng: parseFloat(result.lon),
                    projects: [], // Empty - user will select manually
                    groupId: detectedComarca,
                    services: {
                        mantenimiento: { active: false, expiryDate: null },
                        adm: { active: false, expiryDate: null }
                    }
                };
                
                clients.push(client);
                addedCount++;
                console.log(`✅ Added: ${town} → ${detectedComarca}`);
            } else {
                skippedCount++;
                console.log(`⚠️ Not found: ${town}`);
            }
        } catch (error) {
            console.error(`❌ Error with ${town}:`, error);
            skippedCount++;
        }
        
        // Rate limiting - small delay between requests
        await new Promise(resolve => setTimeout(resolve, 100));
    }
    
    console.log(`\n✅ Batch import complete!`);
    console.log(`Added: ${addedCount}, Skipped: ${skippedCount}`);
    
    // Save to Firebase and update display
    autoSaveToFirebase();
    updateDisplay();
}

// Run the import
batchAddTowns();
